x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3101/api/prom/push'


version: "3.7"

services:

  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    environment:
      GF_FEATURE_TOGGLES_ENABLE: "traceToMetrics"
    ports:
      - 3000:3000
    volumes:
      - ./etc/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./etc/grafana/data:/var/lib/grafana
      - ./etc/grafana:/etc/grafana/provisioning/datasources
      - ./etc/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./etc/grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
    logging: *default-logging
    

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus:/workspace
    command: 
      - "--enable-feature=remote-write-receiver"
      - "--enable-feature=exemplar-storage"
      - --config.file=/workspace/prometheus.yml
    depends_on:
      - loki
    logging: *default-logging

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor
    ports:
      - 8080:8080
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki
    logging: *default-logging

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - 3101:3100
    command: -config.file=/etc/loki/local-config.yaml



  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    volumes:
      - ./etc/tempo/tempo.yaml:/etc/tempo/config.yaml
    command: -config.file=/etc/tempo/config.yaml
    ports:
      - "3100"
      - "4317"
      - "4318"
   

  app_express:
    build: ./app_express/
    container_name: app_express
    ports:
      - "8000:8000"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://tempo:4318
      - OTEL_SERVICE_NAME=express-app
    command: "npm start"
    depends_on:
      - loki
    logging: *default-logging


