{
 "title": "Express Observability",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app_name", "label": "Application Name", "query": { "query": "label_values(app_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_requests_total{app_name=\"$app_name\" ,route!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{app_name=\"$app_name\",route!=\"/metrics\"}",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Request Average Duration",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_request_times_sum{app_name=\"$app_name\"} / http_request_times_count{app_name=\"$app_name\"}",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Total Exceptions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "express_exception_total{app_name=\"$app_name\"}",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Percent of 2xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(route) (http_responses_total{app_name=\"$app_name\", status=~\"2.*\", route!=\"/metrics\"}) /sum by(route) (http_responses_total{app_name=\"$app_name\", route!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Percent of 5xx Requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by(route)(http_responses_total{app_name=\"$app_name\", status=~\"5.*\", route!=\"/metrics\"}) /sum by(route)(http_responses_total{app_name=\"$app_name\", route!=\"/metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PR 99 Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(.99,sum(rate(http_request_times_bucket{route!=\"/metrics\"}[1m])) by(route,le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request In Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "http_requests_in_process{app_name=\"$app_name\", route!=\"/metrics\"}",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(http_requests_total{app_name=\"$app_name\", route!=\"/metrics\"}[1m])",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Log Type Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum by(type) (rate({compose_service=\"$app_name\"} | pattern `<type>: <request_type>, \"trace_id\":\"<trace_id>\", \"span_id\":\"<span_id>\",<msg>` | msg!~\".*/metrics.*\" | type=~\"info\" [1m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by(type) (rate({compose_service=\"$app_name\"} | pattern `<type>: <request_type>, \"trace_id\":\"<trace_id>\", \"span_id\":\"<span_id>\",<msg>` | msg!~\".*/metrics.*\" | type=~\"error\" [1m]))",
     "legendFormat": "{{type}}"
    },
    {
     "expr": "sum by(type) (rate({compose_service=\"$app_name\"} | pattern `<type>: <request_type>, \"trace_id\":\"<trace_id>\", \"span_id\":\"<span_id>\",<msg>` | msg!~\".*/metrics.*\" | type=~\"warn\" [1m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Log of All APP",
   "type": "logs",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "{compose_service=\"$app_name\"} | pattern `<type>: <request_type>, \"trace_id\":\"<trace_id>\", \"span_id\":\"<span_id>\",<msg>` | msg!~\".*/metrics.*\""
    }
   ]
  }
 ]
}